def halloween_night():
    blank1 = raw_input("adjective")
    blank2 = raw_input("adjective")

    print("It was a %r and %r Halloween night." % (blank1, blank2))
halloween_night()


def christmas_tree():
    blank1 = raw_input("month")
    blank2 = raw_input("verb")
    blank3 = raw_input("place")
    blank4 = raw_input("adjective")
    blank5 = raw_input("adjective")
    blank6 = raw_input("place")
    blank7 = raw_input("verb")
    blank8 = raw_input("noun")
    blank9 = raw_input("verb")
    blank10 = raw_input("noun")
    blank11 = raw_input("adjective")
    blank12 = raw_input("adjectve")
    blank13 = raw_input("color")
    blank14 = raw_input("adjectve")
    blank15 = raw_input("verb")
    blank16 = raw_input("verb")
    blank17 = raw_input("noun")
    blank18 = raw_input("exclamation")
    blank19 = raw_input("holiday")

    print("Every %r we %r to a tree %r far away." % (blank1, blank2, blank3))
    print("Not just any %r farm, a %r tree %r." % (blank4, blank5, blank6))
    print("My dad and I %r onto the %r to %r for the perfect %r." % (blank7, blank8, blank9, blank10))
    print("Some people like them %r and %r and some like them %r and fat." % (blank11, blank12, blank13))
    print("We are searching for a tall and %r one! Over there! I exclaim, Dad its's over there! Off we %r, saw in hand to %r this year's %r down. " % (blank14, blank15, blank16, blank17))
    print("%r its's %r finally" % (blank18, blank19))
christmas_tree()

def bike_riding!():
    blank1 = raw_input("verb/ing")
    blank2 = raw_input("adjective")
    blank3 = raw_input("verb/ing")
    blank4 = raw_input("part of body")
    blank5 = raw_input("adverb")
    blank6 = raw_input("part of body")
    blank7 = raw_input("nouns")
    blank8 = raw_input("verb")
    blank9 = raw_input("animals")
    blank10 = raw_input("noun")
    blank11 = raw_input("verb")
    blank12 = raw_input("adjective")
    blank13 = raw_input("color")

    print("%r is a/an %r form of exercise." % (blank1, blank2))
    print("%r a bicycle enables you to develop your %r muscles as well as %r increase the rate of your %r beat." % (blank3, blank4, blank5, blank6))
    print("More %r around the world %r bicycles than drive %r." % (blank7, blank8, blank9))
    print("No matter what kind of %r you %r, always be sure to wear a/an %r helmet." % (blank10, blank11, blank12))
    print("Make sure to have %r reflectors too!" % (blank13))
bike_riding()

def Its_your_birthday():
    blank1 = raw_input("noun")
    blank2 = raw_input("verb")
    blank3 = raw_input("noun")
    blank4 = raw_input("expletive")

    print("Go %r, its's your birthday!" % (blank1))
    print("We gon' %r like its's yo birthday!" % (blank2))
    print("We gonna sip %r like its's your birthday!" % (blank4))
    print("And you know we don't give a %r cause" % (blank5))
Its_your_birthday()

def Excused():
    blank1 = raw_input("name")
    blank2 = raw_input("part of the body")
    blank3 = raw_input("type of fluid")
    blank4 = raw_input("a substance")

    print("%r is sick with the %r flu." % (blank1, blank2))
    print("Drink more %r and take %r as needed" % (blank3, blank4))
Excused()

def The_family_visit():
    blank1 = raw_input("adjective")
    blank2 = raw_input("adjective")
    blank3 = raw_input("person")
    blank4 = raw_input("nouns")
    blank5 = raw_input("noun")
    blank6 = raw_input("noun")
    blank7 = raw_input("verb")
    blank8 = raw_input("vegetables")
    blank9 = raw_input("color")
    blank10 = raw_input("adjective")
    blank11 = raw_input("noun")

    print("We are having a perfectly %r time this afternoon in the %r home of %r" % (blank1, blank2, blank3))
    print("The rooms are decorated with %r for the holidays." % (blank4))
    print("We will feast on %r and corn on the %r." % (blank5, blank6))
    print("After the big feast we will %r alot of %r pie and %r cake." % (blank7, blank8, blank9))
    print("Everyone retreats to the %r sofa to watch %r" % (blank10, blank11))
The_family_visit()

def Crazy_flight():
    blank1 = raw_input("verb ending in ing")
    blank2 = raw_input("plural noun")
    blank3 = raw_input("adjective")

    print("There are too many %r %r on this %r plane! he screamed" % (blank1, blank2, blank3))
Crazy_flight()

def Our_company():
    blank1 = raw_input("goal")
    blank2 = raw_input("goal")
    blank3 = raw_input("adjective")
    blank4 = raw_input("adjective")
    blank5 = raw_input("audience description")
    blank6 = raw_input("emotion")
    blank7 = raw_input("emotion")
    blank8 = raw_input("task")
    blank9 = raw_input("task")

    print("%r and %r by providing %r and %r content that makes %r fell %r or %r so that they can %r or %r." % (blank1, blank2, blank3, blank4, blank5, blank6, blank7, blank8, blank9))
Our_company()

def Pumpkin_Picking!():
    blank1 = raw_input("noun")
    blank2 = raw_input("color")
    blank3 = raw_input("color")
    balnk4 = raw_input("noun")
    blank5 = raw_input("adjective")
    blank6 = raw_input("noun")
    blank7 = raw_input("vegetable")
    blank8 = raw_input("person")
    blank9 = raw_input("verb")
    blank10 = raw_input("adjectve")
    blank11 = raw_input("vegetable")
    blank12 = raw_input("adjectve")
    blank13 = raw_input("vegetable")
    blank14 = raw_input("noun")
    blank15 = raw_input("exclamation")
    blank16 = raw_input("adjectve")

    print("Fall has arrived witth a chill in the %r." % (blank1))
    print("The leaves are turning %r and %r." % (blank2, blank3))
    print("Night time comes quicker, which usually means %r!" % (blank4))
    print("But today was a %r day." % (blank5))
    print("My %r went to the %r patch." % (blank6, blank7))
    print("The %r took us on a hay %r to a big %r field." % (blank8, blank9, blank10))
    print("We all got to pick a %r, that was %r!" % (blank11, blank12))
    print("Yes night comes quicker now that was it's fall.")
    print("But tonight my %r sits by my %r." % (blank13, blank14))
    print("%r what a %r day!" % (blank15, blank16))
Pumpkin_Picking!()

def This_place():
    blank1 = raw_input("place")
    blank2 = raw_input("noun")
    blank3 = raw_input("noun")
    blank4 = raw_input("smaller place within")
    blank5 = raw_input("color")
    blank6 = raw_input("design")
    blank7 = raw_input("noun")
    blank8 = raw_input("-ing word")
    blank9 = raw_input("number")
    blank10 = raw_input("plural noun")
    blank11 = raw_input("different small place within")

    print("I know this %r, by heart." % (blank1))
    print("I know every %r, I know the colour of the %r in the %r, %r, with a %r." % (blank2, blank3, blank4, blank5, blank6))
    print("I know that the %r is %r the bathroom window frame and the there are %r %r missing from %r on the right-hand side." % (blank7, blank8, blank9, blank10, blank11))
This_place()

    
